"use client";

/**
 * Bulk product import from a spreadsheet.
 *
 * The flow is deliberately three steps — download, fill, upload — because the
 * failure this screen exists to prevent is a user building their own file and
 * discovering after the fact that the column names did not match. The template
 * is generated by the server with the live category and unit codes in it, so
 * the file the user fills in is by construction the file the parser reads.
 *
 * Upload never writes on the first call. The server validates and returns a
 * report, this dialog renders it, and only an explicit second click commits.
 * That preview is what makes the destructive action deliberate rather than a
 * side effect of choosing a file.
 */

import {
  AlertTriangle,
  CheckCircle2,
  Download,
  FileSpreadsheet,
  Upload,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogBody,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Alert, Badge } from "@/components/ui/primitives";
import { toast } from "@/components/ui/toast";
import { ApiError, api, saveBlob } from "@/lib/api/client";
import type { ImportFormat, ImportReport } from "@/lib/api/types";
import { translateError } from "@/lib/hooks";
import type { Dictionary } from "@/lib/i18n/dictionaries";
import { useTranslation } from "@/lib/i18n/provider";

const ENDPOINT = "/catalog/medicines/";

/**
 * Translate a caught value, which TypeScript types as `unknown`.
 *
 * Anything that is not an `ApiError` — a bug in this component rather than a
 * refusal from the server — falls back to the generic message rather than
 * leaking a stack trace into a toast.
 */
function asApiError(error: unknown, t: Dictionary): string {
  return (
    (error instanceof ApiError ? translateError(error, t) : null) ??
    t.common.errorOccurred
  );
}

export function ImportDialog({
  open,
  onOpenChange,
  onImported,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** Fired after a successful commit so the list behind the dialog refreshes. */
  onImported: () => void;
}) {
  const t = useTranslation();
  const fileInput = useRef<HTMLInputElement>(null);

  const [format, setFormat] = useState<ImportFormat | null>(null);
  const [showFormat, setShowFormat] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  const [report, setReport] = useState<ImportReport | null>(null);
  const [busy, setBusy] = useState<"none" | "template" | "checking" | "importing">(
    "none",
  );

  // The column spec comes from the server rather than being duplicated here,
  // so the format this dialog documents cannot drift from the one the parser
  // enforces. Fetched on open because it is only needed once the user looks.
  useEffect(() => {
    if (!open || format) return;
    api
      .get<ImportFormat>(`${ENDPOINT}import-format/`)
      .then(setFormat)
      // A failed spec fetch degrades the help text but must not block the
      // import itself, which is what the user actually came for.
      .catch(() => undefined);
  }, [open, format]);

  const reset = () => {
    setFile(null);
    setReport(null);
    setBusy("none");
    if (fileInput.current) fileInput.current.value = "";
  };

  const handleOpenChange = (next: boolean) => {
    if (!next) reset();
    onOpenChange(next);
  };

  const downloadTemplate = async () => {
    setBusy("template");
    try {
      const blob = await api.download(`${ENDPOINT}import-template/`);
      saveBlob(blob, "modele-import-produits.xlsx");
    } catch (error) {
      toast.error(t.common.errorOccurred, asApiError(error, t));
    } finally {
      setBusy("none");
    }
  };

  /** Uploads the file; `dryRun` false is the committing call. */
  const send = async (dryRun: boolean) => {
    if (!file) return;
    setBusy(dryRun ? "checking" : "importing");

    const body = new FormData();
    body.append("file", file);
    body.append("dry_run", String(dryRun));

    try {
      const result = await api.post<ImportReport>(`${ENDPOINT}import/`, body);
      setReport(result);

      if (result.committed) {
        toast.success(
          t.import.successTitle,
          [
            result.created > 0 && `${result.created} ${t.import.createdCount}`,
            result.updated > 0 && `${result.updated} ${t.import.updatedCount}`,
          ]
            .filter(Boolean)
            .join(" · "),
        );
        onImported();
        handleOpenChange(false);
      }
    } catch (error) {
      // A 422 carries a parsed report in its details — an unreadable file, or
      // a missing column. Rendering it in place is more useful than a toast,
      // because the message names the column the user has to add.
      if (error instanceof ApiError && error.details?.fatal_error) {
        setReport(error.details as unknown as ImportReport);
      } else {
        toast.error(t.common.errorOccurred, asApiError(error, t));
      }
    } finally {
      setBusy("none");
    }
  };

  const onFileChosen = (event: React.ChangeEvent<HTMLInputElement>) => {
    const chosen = event.target.files?.[0] ?? null;
    setFile(chosen);
    // A new file invalidates the previous verdict; leaving it on screen would
    // invite committing one file on the strength of another's preview.
    setReport(null);
  };

  const canCommit =
    report !== null &&
    !report.committed &&
    !report.fatal_error &&
    report.error_count === 0 &&
    report.valid_count > 0;

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent size="xl">
        <DialogHeader>
          <DialogTitle>{t.import.title}</DialogTitle>
          <DialogDescription>{t.import.subtitle}</DialogDescription>
        </DialogHeader>

        <DialogBody className="space-y-5">
          {/* --- Step 1: the template ------------------------------------ */}
          <section className="rounded-lg border border-border p-4">
            <div className="flex flex-wrap items-start justify-between gap-3">
              <div className="min-w-0">
                <p className="text-sm font-medium">{t.import.step1}</p>
                <p className="mt-1 text-sm text-muted-foreground">
                  {t.import.downloadTemplateHint}
                </p>
              </div>
              <Button
                variant="outline"
                onClick={downloadTemplate}
                loading={busy === "template"}
                disabled={busy !== "none"}
              >
                <Download className="h-4 w-4" />
                {t.import.downloadTemplate}
              </Button>
            </div>
          </section>

          {/* --- Step 2: the format spec --------------------------------- */}
          <section className="rounded-lg border border-border p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <p className="text-sm font-medium">{t.import.step2}</p>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowFormat((value) => !value)}
              >
                {showFormat ? t.import.hideFormat : t.import.showFormat}
              </Button>
            </div>

            {showFormat && format && (
              <div className="mt-3 space-y-3">
                <div className="flex flex-wrap items-center gap-4 text-xs text-muted-foreground">
                  <span className="flex items-center gap-1.5">
                    <span className="inline-block h-2.5 w-2.5 rounded-sm bg-warning" />
                    {t.import.requiredLegend}
                  </span>
                  <span className="flex items-center gap-1.5">
                    <span className="inline-block h-2.5 w-2.5 rounded-sm bg-primary" />
                    {t.import.optionalLegend}
                  </span>
                </div>

                {/* Scrolls on its own so a 26-column spec never makes the
                    dialog itself scroll sideways. */}
                <div className="max-h-72 overflow-auto rounded-md border border-border">
                  <table className="w-full text-sm">
                    <thead className="sticky top-0 bg-muted">
                      <tr className="text-left">
                        <th className="px-3 py-2 font-medium">
                          {t.import.formatColumn}
                        </th>
                        <th className="px-3 py-2 font-medium">
                          {t.import.formatDescription}
                        </th>
                        <th className="px-3 py-2 text-right font-medium">
                          {t.common.status}
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {format.columns.map((column) => (
                        <tr
                          key={column.key}
                          className="border-t border-border align-top"
                        >
                          <td className="px-3 py-2">
                            <span className="font-medium">{column.header}</span>
                            {column.example && (
                              <p className="mt-0.5 font-mono text-xs text-muted-foreground">
                                {column.example}
                              </p>
                            )}
                          </td>
                          <td className="px-3 py-2 text-muted-foreground">
                            {column.hint}
                          </td>
                          <td className="px-3 py-2 text-right">
                            {column.required && (
                              <Badge variant="warning">
                                {t.import.formatRequired}
                              </Badge>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                <p className="text-xs text-muted-foreground">
                  {t.import.updateNote}
                </p>
              </div>
            )}
          </section>

          {/* --- Step 3: the upload -------------------------------------- */}
          <section className="rounded-lg border border-border p-4">
            <p className="text-sm font-medium">{t.import.step3}</p>

            <div className="mt-3 flex flex-wrap items-center gap-3">
              <input
                ref={fileInput}
                type="file"
                accept=".xlsx,.xlsm,.csv,.txt"
                onChange={onFileChosen}
                className="sr-only"
                id="catalogue-import-file"
              />
              <Button
                variant="outline"
                onClick={() => fileInput.current?.click()}
                disabled={busy !== "none"}
                type="button"
              >
                <Upload className="h-4 w-4" />
                {file ? t.import.changeFile : t.import.chooseFile}
              </Button>

              {file && (
                <span className="flex min-w-0 items-center gap-2 text-sm">
                  <FileSpreadsheet className="h-4 w-4 shrink-0 text-muted-foreground" />
                  <span className="truncate">{file.name}</span>
                </span>
              )}
            </div>

            <p className="mt-2 text-xs text-muted-foreground">
              {t.import.dropHint}
            </p>
          </section>

          {/* --- The verdict --------------------------------------------- */}
          {report?.fatal_error && (
            <Alert variant="destructive" title={t.common.errorOccurred}>
              {report.fatal_error}
            </Alert>
          )}

          {report && !report.fatal_error && (
            <div className="space-y-3">
              <div className="flex flex-wrap items-center gap-3 text-sm">
                <span className="flex items-center gap-1.5">
                  <CheckCircle2 className="h-4 w-4 text-success" />
                  {report.valid_count} {t.import.rowsReady}
                </span>
                {report.error_count > 0 && (
                  <span className="flex items-center gap-1.5 text-destructive">
                    <AlertTriangle className="h-4 w-4" />
                    {report.error_count} {t.import.rowsInError}
                  </span>
                )}
              </div>

              {report.error_count === 0 ? (
                <Alert variant="success">{t.import.noErrors}</Alert>
              ) : (
                <>
                  <Alert variant="warning">{t.import.nothingImported}</Alert>

                  <div className="max-h-64 overflow-auto rounded-md border border-border">
                    <table className="w-full text-sm">
                      <thead className="sticky top-0 bg-muted">
                        <tr className="text-left">
                          <th className="w-20 px-3 py-2 font-medium">
                            {t.import.row}
                          </th>
                          <th className="px-3 py-2 font-medium">
                            {t.catalog.name}
                          </th>
                          <th className="px-3 py-2 font-medium">
                            {t.import.errorsTitle}
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {report.errors.map((row) => (
                          <tr
                            key={row.row_number}
                            className="border-t border-border align-top"
                          >
                            <td className="px-3 py-2 font-mono text-xs">
                              {row.row_number}
                            </td>
                            <td className="px-3 py-2">{row.name}</td>
                            <td className="px-3 py-2">
                              <ul className="space-y-0.5 text-destructive">
                                {Object.entries(row.errors).map(
                                  ([field, messages]) => (
                                    <li key={field}>{messages.join(" ")}</li>
                                  ),
                                )}
                              </ul>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>

                  {/* The server caps the error list; without this note a user
                      with 500 bad rows would fix 200 and expect to be done. */}
                  {report.error_count > report.errors.length && (
                    <p className="text-xs text-muted-foreground">
                      … {report.error_count - report.errors.length}{" "}
                      {t.import.andMore}
                    </p>
                  )}
                </>
              )}
            </div>
          )}

          <p className="text-xs text-muted-foreground">{t.import.allOrNothing}</p>
        </DialogBody>

        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => handleOpenChange(false)}
            disabled={busy === "importing"}
          >
            {t.common.cancel}
          </Button>

          {canCommit ? (
            <Button
              onClick={() => send(false)}
              loading={busy === "importing"}
              disabled={busy !== "none"}
            >
              {t.import.confirmImport}
            </Button>
          ) : (
            <Button
              onClick={() => send(true)}
              loading={busy === "checking"}
              disabled={!file || busy !== "none"}
            >
              {t.import.verify}
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
